### ISSUE TITLE
pertino-client 520-4587 does not support upstart

### ISSUE THREAD

**Issue by JCzarniecki** [miketheman/pertino-cookbook#1]
Hello,

Pertino Client ubuntu repository got recently updated and the only version available is 520-4587 which seems not to offer upstart configuration.

It means that version 0.1.1 is no longer working - if upstart provider is forced in service, then the whole run fails.

On version 0.1.0 this problem is not present.
I see that forcing Upstart provider was in order to support Chef 11, but right now it causes all Chef versions to fail with 0.1.1 of this cookbook.

I suggest reverting this change or changing to supported provider.

**Comment by miketheman** [comment]
Hi @JCzarniecki ! Thanks for reporting.
- Can you show some more details of the error condition, on how this is surfaced?
- What service runner does the 520-4587 version provide?

**Comment by JCzarniecki** [comment]
Hi @miketheman ! Thank you for a very quick response.

> Multiple failures occurred:
> - ArgumentError occurred in chef run: service[pgateway](/var/cache/chef/cookbooks/pertino/libraries/provider_pertino_client.rb line 50) had an error: ArgumentError: File '/etc/init/pgateway.conf' does not exist
> - Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: service[pgateway](/var/cache/chef/cookbooks/pertino/libraries/provider_pertino_client.rb line 50) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
>   ---- Begin output of /sbin/start pgateway ----
>   STDOUT: 
>   STDERR: start: Unknown job: pgateway
>   ---- End output of /sbin/start pgateway ----
>   Ran /sbin/start pgateway returned 1

I have confirmed that the new version does not install upstart job (initctl list does not contain pgateway) while old version was providing upstart job just fine.

So it looks like the new pertino-client package provides only service for SysVinit (/etc/init.d/pgateway).

**Comment by miketheman** [comment]
I've confirmed the behavioral change on a recent version.

The upstart file is still provided in the package, but not put into place during install.

```
$ dpkg-query -L pertino-client | grep init
/opt/pertino/pgateway/init
/opt/pertino/pgateway/init/pgateway.conf
/opt/pertino/pgateway/init/pgateway
/opt/pertino/pgateway/init/pgateway_service.sh
/opt/pertino/pgateway/init/pgateway.service
/opt/pertino/pgateway/init/pgateway-service.sh
```

It also appears that `pgateway_service.sh` and `pgateway-service.sh` are identical - that's a bit odd.

So if the package is going to copy, not symlink, the service script, and I'm guessing something changed upstream that controls this behavior. I was unable to find any release notes.

I'm updating my test suite now to get this back on track, and should be able to release a change soon.

**Comment by tkrautkremer** [comment]
JC and Mike, thanks for reporting. We are looking into it and will provide an update on the situation here shortly.

-- Pertino
